"use client";
import { useMemo, useState } from "react";
import { api } from "../lib/api";

export default function KitEditor({kit:initial,onUpdate}:{kit:any;onUpdate:(k:any)=>void}) {
  const [kit,setKit]=useState(initial); const [tab,setTab]=useState("overview");
  const [practiceIndex,setPracticeIndex]=useState(0); const [editing,setEditing]=useState<string|null>(null);
  const [saving,setSaving]=useState(false); const [briefEdit,setBriefEdit]=useState(false);
  const [regen,setRegen]=useState(false);
  const cards=useMemo(()=>[...(kit.flashcards||[])].sort((a:any,b:any)=>(a.confidence??0)-(b.confidence??0)),[kit.flashcards]);
  const update=(k:any)=>{setKit(k);onUpdate(k)};

  async function saveQuestion(q:any){
    setSaving(true); try{const d=await api(`/api/kits/${kit._id}/question/${q.id}`,{method:"PATCH",body:JSON.stringify({prompt:q.prompt,answer_outline:q.answer_outline,category:q.category,difficulty:q.difficulty})});update(d.kit);setEditing(null)}catch(e:any){alert(e.message)}finally{setSaving(false)}
  }
  async function removeQuestion(id:string){if(!confirm("Delete this question?"))return;const d=await api(`/api/kits/${kit._id}/question/${id}`,{method:"DELETE"});update(d.kit)}
  async function addQuestion(){const prompt=window.prompt("Question");if(!prompt)return;const d=await api(`/api/kits/${kit._id}/question`,{method:"POST",body:JSON.stringify({prompt,answer_outline:"",category:"technical",difficulty:2})});update(d.kit)}
  async function addCard(){const front=window.prompt("Flashcard front");if(!front)return;const back=window.prompt("Flashcard answer");if(!back)return;const d=await api(`/api/kits/${kit._id}/flashcard`,{method:"POST",body:JSON.stringify({front,back})});update(d.kit)}
  async function removeCard(id:string){if(!confirm("Delete this flashcard?"))return;const d=await api(`/api/kits/${kit._id}/flashcard/${id}`,{method:"DELETE"});update(d.kit)}
  async function saveBrief(){const d=await api(`/api/kits/${kit._id}/company-brief`,{method:"PATCH",body:JSON.stringify(kit.company_brief)});update(d.kit);setBriefEdit(false)}
  async function regenerate(section:string,category?:string){setRegen(true);try{const d=await api(`/api/kits/${kit._id}/regenerate`,{method:"POST",body:JSON.stringify({section,category})});update(d.kit)}catch(e:any){alert(e.message)}finally{setRegen(false)}}
  async function reorder(id:string,dir:number){const arr=[...kit.questions];const i=arr.findIndex((q:any)=>q.id===id);const j=i+dir;if(j<0||j>=arr.length)return;[arr[i],arr[j]]=[arr[j],arr[i]];const d=await api(`/api/kits/${kit._id}/reorder`,{method:"PATCH",body:JSON.stringify({question_ids:arr.map((q:any)=>q.id)})});update(d.kit)}
  async function confidence(v:number){const card=cards[practiceIndex];if(!card)return;try{const d=await api(`/api/kits/${kit._id}/confidence/${card.id}`,{method:"PATCH",body:JSON.stringify({confidence:v})});update(d.kit);if(practiceIndex<cards.length-1)setPracticeIndex(x=>x+1)}catch(e:any){alert(e.message)}}

  const tabs=["overview","questions","flashcards","schedule","practice"];
  return <div>
    <div className="mb-5 flex flex-wrap gap-2">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-xl px-4 py-2 text-sm font-bold ${tab===t?"bg-slate-900 text-white":"bg-white text-slate-600 shadow-sm"}`}>{t}</button>)}</div>

    {tab==="overview"&&<div className="grid gap-5 lg:grid-cols-2">
      <section className="rounded-2xl bg-white p-6 shadow-sm lg:col-span-2">
        <div className="flex items-center justify-between"><div><div className="text-xs font-black uppercase text-indigo-600">Company brief</div><h2 className="mt-1 text-2xl font-black">{kit.source.company}</h2></div><div className="flex gap-2"><button disabled={regen} onClick={()=>setBriefEdit(!briefEdit)} className="rounded-lg bg-slate-100 px-3 py-2 text-sm font-bold">{briefEdit?"Cancel":"Edit"}</button><button disabled={regen} onClick={()=>regenerate("company_brief")} className="rounded-lg bg-indigo-50 px-3 py-2 text-sm font-bold text-indigo-700">Regenerate</button></div></div>
        {briefEdit?<><textarea className="mt-4 min-h-24 w-full rounded-xl border p-3" value={kit.company_brief.summary} onChange={e=>setKit({...kit,company_brief:{...kit.company_brief,summary:e.target.value}})}/><textarea className="mt-3 min-h-24 w-full rounded-xl border p-3" value={kit.company_brief.what_they_do} onChange={e=>setKit({...kit,company_brief:{...kit.company_brief,what_they_do:e.target.value}})}/><button onClick={saveBrief} className="mt-3 rounded-xl bg-slate-900 px-4 py-2 font-bold text-white">Save brief</button></>:<><p className="mt-3 text-slate-600">{kit.company_brief.summary}</p><p className="mt-3 text-slate-600">{kit.company_brief.what_they_do}</p></>}
      </section>
      <section className="rounded-2xl bg-white p-6 shadow-sm"><div className="text-xs font-black uppercase text-indigo-600">Role</div><h2 className="mt-2 text-2xl font-black">{kit.role.title}</h2><p className="text-slate-500">{kit.role.seniority}</p><div className="mt-4 space-y-2">{kit.role.requirements.map((r:any)=><div key={r.id} className="rounded-xl bg-slate-50 p-3 text-sm"><b>{r.id}</b> {r.text}<span className="ml-2 rounded-full bg-white px-2 py-1 text-xs">{r.priority}</span></div>)}</div></section>
      <section className="rounded-2xl bg-white p-6 shadow-sm"><h3 className="font-black">Coverage</h3><p className="mt-2 text-slate-600">{kit.coverage.uncovered_requirement_ids.length?"Gaps: "+kit.coverage.uncovered_requirement_ids.join(", "):"All must-have requirements are covered."}</p><p className="mt-2 text-sm text-slate-400">Coverage passes: {kit.coverage.passes}</p></section>
    </div>}

    {tab==="questions"&&<div><div className="mb-4 flex flex-wrap gap-2"><button onClick={addQuestion} className="rounded-xl bg-slate-900 px-4 py-2 font-bold text-white">+ Add question</button>{["technical","behavioural","system-design","company-fit"].map(c=><button disabled={regen} key={c} onClick={()=>regenerate("questions",c)} className="rounded-xl bg-white px-3 py-2 text-sm font-bold shadow-sm">Regenerate {c}</button>)}</div><div className="space-y-4">{kit.questions.map((q:any,i:number)=><div key={q.id} className="rounded-2xl bg-white p-5 shadow-sm">
      {editing===q.id?<div><textarea className="min-h-24 w-full rounded-xl border p-3" value={q.prompt} onChange={e=>setKit({...kit,questions:kit.questions.map((x:any)=>x.id===q.id?{...x,prompt:e.target.value}:x)})}/><textarea className="mt-3 min-h-24 w-full rounded-xl border p-3" value={q.answer_outline} onChange={e=>setKit({...kit,questions:kit.questions.map((x:any)=>x.id===q.id?{...x,answer_outline:e.target.value}:x)})}/><div className="mt-3 grid gap-3 sm:grid-cols-2"><select className="rounded-xl border p-3" value={q.category} onChange={e=>setKit({...kit,questions:kit.questions.map((x:any)=>x.id===q.id?{...x,category:e.target.value}:x)})}>{["technical","behavioural","system-design","company-fit"].map(c=><option key={c}>{c}</option>)}</select><select className="rounded-xl border p-3" value={q.difficulty} onChange={e=>setKit({...kit,questions:kit.questions.map((x:any)=>x.id===q.id?{...x,difficulty:Number(e.target.value)}:x)})}><option value={1}>Difficulty 1</option><option value={2}>Difficulty 2</option><option value={3}>Difficulty 3</option></select></div><div className="mt-3 flex gap-2"><button disabled={saving} onClick={()=>saveQuestion(q)} className="rounded-xl bg-slate-900 px-4 py-2 font-bold text-white">Save</button><button onClick={()=>setEditing(null)} className="rounded-xl bg-slate-100 px-4 py-2 font-bold">Cancel</button></div></div>:<><div className="flex items-start justify-between gap-4"><div><span className="text-xs font-black text-indigo-600">{q.id} • {q.category} • D{q.difficulty}</span><h3 className="mt-1 font-bold">{q.prompt}</h3></div><div className="flex flex-wrap gap-1"><button onClick={()=>reorder(q.id,-1)} className="rounded-lg bg-slate-100 px-2 py-1 text-xs">↑</button><button onClick={()=>reorder(q.id,1)} className="rounded-lg bg-slate-100 px-2 py-1 text-xs">↓</button><button onClick={()=>setEditing(q.id)} className="rounded-lg bg-slate-100 px-2 py-1 text-xs font-bold">Edit</button><button onClick={()=>removeQuestion(q.id)} className="rounded-lg bg-red-50 px-2 py-1 text-xs font-bold text-red-600">Delete</button></div></div><p className="mt-3 text-sm text-slate-600">{q.answer_outline}</p><div className="mt-3 text-xs text-slate-400">Requirements: {q.requirement_ids.join(", ")} • {q._state||"generated"}</div></>}</div>)}</div></div>}

    {tab==="flashcards"&&<div><button onClick={addCard} className="mb-4 rounded-xl bg-slate-900 px-4 py-2 font-bold text-white">+ Add flashcard</button><div className="grid gap-4 md:grid-cols-2">{kit.flashcards.map((f:any)=><div key={f.id} className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex justify-between"><div className="text-xs font-black text-indigo-600">{f.id}</div><button onClick={()=>removeCard(f.id)} className="text-xs font-bold text-red-600">Delete</button></div><h3 className="mt-2 font-black">{f.front}</h3><p className="mt-3 text-sm text-slate-600">{f.back}</p><div className="mt-3 text-xs text-slate-400">Confidence: {f.confidence??"Not practiced"}</div></div>)}</div></div>}

    {tab==="schedule"&&<div><div className="mb-4"><button disabled={regen} onClick={()=>regenerate("schedule")} className="rounded-xl bg-indigo-600 px-4 py-2 font-bold text-white">Regenerate schedule</button></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{kit.schedule.days.map((d:any)=><div key={d.day} className="rounded-2xl bg-white p-5 shadow-sm"><div className="text-xs font-black text-indigo-600">DAY {d.day}</div><h3 className="mt-1 font-black">{d.focus}</h3><p className="mt-2 text-sm text-slate-500">{d.minutes} minutes</p><div className="mt-4 text-xs text-slate-500">{d.question_ids.join(" • ")||"Review"}</div></div>)}</div></div>}

    {tab==="practice"&&<div className="mx-auto max-w-2xl rounded-3xl bg-white p-8 text-center shadow-sm">{cards.length?<><div className="text-xs font-black uppercase text-indigo-600">Weak-first practice • Card {practiceIndex+1} / {cards.length}</div><h2 className="mt-5 text-2xl font-black">{cards[practiceIndex]?.front}</h2><details className="mt-6 rounded-2xl bg-slate-50 p-5 text-left"><summary className="cursor-pointer font-bold">Reveal answer</summary><p className="mt-3 text-slate-600">{cards[practiceIndex]?.back}</p></details><p className="mt-7 text-sm font-bold text-slate-500">How confident are you?</p><div className="mt-3 flex justify-center gap-2">{[1,2,3,4,5].map(v=><button key={v} onClick={()=>confidence(v)} className="rounded-xl bg-slate-900 px-4 py-3 font-bold text-white">{v}</button>)}</div></>:<p>No flashcards.</p>}</div>}
  </div>;
}
